name: Compile PDFs

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: resume/situ2001.tex

    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: examples
    #     path: examples/*.pdf

    - uses: actions/upload-artifact@v3
      with:
        name: situ2001's resume
        path: resume/*.pdf
